# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
  end

  config.vm.define "centos7" do |c7|
    c7.vm.hostname = "c7"
    c7.vm.network "private_network", ip: "172.23.62.92"

    # Disable default /vagrant synced folder
    c7.vm.synced_folder ".", "/vagrant", disabled: true

    # custom synced folder and set permissions
    c7.vm.synced_folder "/path/to/vagrant-centos7/provision", "/provision",
        owner: "root",
        group: "root",
        mount_options: ["dmode=755,fmode=644"]

    c7.vm.synced_folder "/path/to/Projects/vagrant-centos7/ansible", "/ansible",
        owner: "root",
        group: "root",
        mount_options: ["dmode=755,fmode=644"]

    c7.vm.synced_folder "/path/to/Projects/vagrant-centos7/shared", "/shared",
        owner: "root",
        group: "root",
        mount_options: ["dmode=755,fmode=644"]

    c7.vm.synced_folder "/path/to/Projects/vagrant-centos7/docker", "/docker",
        owner: "root",
        group: "root",
        mount_options: ["dmode=755,fmode=644"]

    c7.vm.provision :shell, :path => "provision-cm-redhat.sh"
  end

end
